services:
  # network_monitor:
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile.firewall
  #   container_name: network_monitor
  #   privileged: true # Enables privileged mode to allow sudo-level operations
  #   network_mode: "host" # Allows the container to directly access the host network (necessary for `arp`, `netstat`, etc.)
  #   pid: "host"
  #   volumes:
  #     # - /sys:/sys:ro
  #     # - /proc:/proc:ro
  #     - ./src/server.py:/app/server.py
  #     - ./src/run_tracer.py:/app/run_tracer.py
  #     - ./src/run_controller.py:/app/run_controller.py
  #     - ./src/monitor/:/app/monitor/
  #     - ./src/interceptor/:/app/interceptor/
  #     - ./src/requirements.txt:/app/requirements.txt
  #     - ./src/network_controller/:/app/network_controller/
  #   ports:
  #     - 5000:5000
  #   cap_add:
  #     - NET_ADMIN # Adds the NET_ADMIN capability for networking tasks
  #     - SYS_ADMIN # Adds SYS_ADMIN for additional networking capabilities
  #   environment:
  #     - FLASK_APP=server.py
  #     - FLASK_ENV=production
  #     - PYTHONUNBUFFERED=1
  #     # - NET_RAW
  #     # - SYS_PTRACE
  #   # security_opt:
  #   #   - apparmor=unconfined
  #   # command: python server.py
  #   command: /entrypoint.sh
  #   stdin_open: true # Keeps the stdin open for interactive sessions
  #   tty: true # Allocates a pseudo-TTY
  #   restart: unless-stopped
  mongo-rules:
    image: mongo:7.0
    container_name: db-mongo-interceptor-rules
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongorulesuser
      - MONGO_INITDB_ROOT_PASSWORD=rulespass
    networks:
      - vaidhanik
    ports:
      - "27018:27017"
    volumes:
      - mongo_rules:/data/db

  mongo-attempts:
    image: mongo:7.0
    container_name: db-mongo-interceptor-attempts
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoattemptsuser
      - MONGO_INITDB_ROOT_PASSWORD=attemptspass
    networks:
      - vaidhanik
    ports:
      - "27019:27017"
    volumes:
      - mongo_attempts:/data/db

  mongo-monitor:
    image: mongo:latest
    container_name: network_monitor_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongomonitor
      - MONGO_INITDB_ROOT_PASSWORD=monitorpass
    ports:
      - "27020:27017"
    volumes:
      - mongo_monitor:/data/db
    networks:
      - vaidhanik

  mongo-express-rules:
    image: mongo-express
    container_name: db-mongo-express-rules
    ports:
      - 8081:8081
    networks:
      - vaidhanik
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=MONITOR
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rulespass
      - ME_CONFIG_MONGODB_SERVER=mongo-rules
    depends_on:
      - mongo-rules
      - mongo-monitor
      - mongo-attempts
 
  mongo-express-attempts:
    image: mongo-express
    container_name: db-mongo-express-attempts
    ports:
      - 8082:8081
    networks:
      - vaidhanik
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoattemptsuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=attemptspass
      - ME_CONFIG_MONGODB_SERVER=mongo-attempts
    depends_on:
      - mongo-rules
      - mongo-monitor
      - mongo-attempts
  
  mongo-express-monitor:
    image: mongo-express
    container_name: db-mongo-express-monitor
    ports:
      - 8083:8081
    networks:
      - vaidhanik
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongomonitor
      - ME_CONFIG_MONGODB_ADMINPASSWORD=monitorpass
      - ME_CONFIG_MONGODB_SERVER=mongo-monitor
    depends_on:
      - mongo-rules
      - mongo-monitor
      - mongo-attempts


volumes:
  mongo_rules:
    driver: local
  mongo_attempts:
    driver: local
  mongo_monitor:
    driver: local

networks:
  vaidhanik:
    driver: bridge